[workspace]
resolver = "2"

members = [
  "zomes/hc_cz_profile",
  "zomes/hc_iz_profile",
  "zomes/hc_iz_membrane_manager"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = "=0.6.3"
hdk = "=0.5.3"
holochain_zome_types = "0.5.3"
hc_utils = { git = "https://github.com/alastairong1/hc-utils.git", rev = "04a1623accefc99c2ef5a5898a5af35415764bf6" }
serde = "1.0"
holochain_serialized_bytes = "*"